# Generated by Django 6.0.7 on 2026-10-06 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_invoice_due_amount_remove_invoice_paid_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='due',
            new_name='due_amount',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='paid',
            new_name='paid_amount',
        ),
    ]
