# Generated by Django 6.0.7 on 2026-10-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_shopsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
