# Generated by Django 6.0.7 on 2026-10-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_expensecategory_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='expense_type',
        ),
    ]
