# Generated by Django 6.0.7 on 2026-09-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_billing_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='order_type',
        ),
    ]
